Repository astrocamp/19th-FitCal, pull requests merged in 2025-05, with the labels that each got.

#32 fix: 修正 PR #12 rebase 到 dev 後執行會出現 error 跟 bug 的問題
  fitcal/urls.py
  orders/templatetags/datetime_format.py
Labels: bug

#104 修正靜態檔案讀取的錯誤
  fitcal/settings.py
Labels: bug, 優先確認

#108 修復： store無法更新的問題
  stores/views.py
  templates/stores/edit.html
Labels: bug, 優先確認

#124 商品加入購物車功能及介面
  carts/urls.py
  carts/views.py
  package-lock.json
  products/views.py
  templates/products/show.html
Labels: 優先確認, 切版

#126 主頁/網站介紹頁切版
  templates/pages/index.html
Labels: 切版
